programa=p7

$(programa): ./src/main.c ./src/argumentos.c ./src/potencia.c ./include/argumentos.h 
	gcc -o $(programa) -g ./src/main.c ./src/argumentos.c ./src/potencia.c -I./include -lm -Wall -Wextra
